# Generated by Django 4.2.2 on 2023-07-19 15:53

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('material_disc', models.CharField(max_length=255)),
                ('document', models.FileField(null=True, upload_to='course_materials/documents')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learningapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quiz_start_date', models.DateTimeField()),
                ('quiz_due_date', models.DateTimeField()),
                ('marks', models.IntegerField(default=0)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learningapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('0', 'Student'), ('1', 'Professor')], default='0', max_length=255, null=True)),
                ('memberShip', models.CharField(choices=[('F', 'Free'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Premium')], default='F', max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('none', 'None'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='learningapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('related_id', models.CharField(max_length=255)),
                ('assignment_grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learningapp.material')),
                ('quiz_grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learningapp.quiz')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learningapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learningapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learningapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.CharField(max_length=255)),
                ('submission_date', models.DateField()),
                ('material_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learningapp.material')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learningapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', to='learningapp.users'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_tutored', to='learningapp.users'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(null=True, upload_to='course_materials/documents')),
                ('due_date', models.DateField(null=True)),
                ('due_time', models.TimeField(null=True)),
                ('grade', models.PositiveIntegerField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.course')),
            ],
        ),
    ]
