# Generated by Django 4.2.2 on 2023-07-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_remove_course_enrolled_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='aaignment_grade',
        ),
        migrations.RemoveField(
            model_name='material',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='material',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='material',
            name='video',
        ),
    ]
