# Generated by Django 4.2.2 on 2023-07-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_remove_materialanswer_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialanswer',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.material'),
        ),
        migrations.AlterField(
            model_name='materialanswer',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.users'),
        ),
    ]
