# Generated by Django 4.2.2 on 2023-07-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0003_alter_materialanswer_material_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='description',
            new_name='quiz_data',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_due_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_start_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
