# Generated by Django 4.2.2 on 2023-07-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0003_remove_material_aaignment_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='assignment',
        ),
    ]
