# Generated by Django 4.2.2 on 2023-07-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0004_remove_material_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='document',
        ),
    ]
