# Generated by Django 4.2.2 on 2023-07-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0005_remove_material_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='document',
            field=models.FileField(null=True, upload_to='course_materials/documents'),
        ),
    ]
