# Generated by Django 4.2.2 on 2023-07-18 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0006_material_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(null=True, upload_to='course_materials/documents')),
                ('due_date', models.DateTimeField()),
                ('grade', models.PositiveIntegerField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.course')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.material')),
            ],
        ),
    ]
