# Generated by Django 4.2.2 on 2023-07-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0007_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='material_id',
        ),
    ]
